<a href="https://colab.research.google.com/github/Sharzzdevise/Projects/blob/main/Stage_C_quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Import all libraries needed

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
#load the dataset

grid_data = pd.read_csv("Data_for_UCI_named.csv")
grid_data

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,unstable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,stable
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,unstable
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,unstable

In [4]:
#preliminary data exploration

grid_data.shape

(10000, 14)

In [5]:
grid_data.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [6]:
grid_data.duplicated().sum()

0

In [7]:
grid_data.describe().T

,count,mean,std,min,25%,50%,75%,max
tau1,10000.0,5.250000,2.742548,0.500793,2.874892,5.250004,7.624690,9.999469
tau2,10000.0,5.250001,2.742549,0.500141,2.875140,5.249981,7.624893,9.999837
tau3,10000.0,5.250004,2.742549,0.500788,2.875522,5.249979,7.624948,9.999450
tau4,10000.0,5.249997,2.742556,0.500473,2.874950,5.249734,7.624838,9.999443
p1,10000.0,3.750000,0.752160,1.582590,3.218300,3.751025,4.282420,5.864418
p2,10000.0,-1.250000,0.433035,-1.999891,-1.624901,-1.249966,-0.874977,-0.500108
p3,10000.0,-1.250000,0.433035,-1.999945,-1.625025,-1.249974,-0.875043,-0.500072
p4,10000.0,-1.250000,0.433035,-1.999926,-1.624960,-1.250007,-0.875065,-0.500025
g1,10000.0,0.525000,0.274256,0.050009,0.287521,0.525009,0.762435,0.999937
g2,10000.0,0.525000,0.274255,0.050053,0.287552,0.525003,0.762490,0.999944
g3,10000.0,0.525000,0.274255,0.050054,0.287514,0.525015,0.762440,0.999982
g4,10000.0,0.525000,0.274255,0.050028,0.287494,0.525002,0.762433,0.999930
stab,10000.0,0.015731,0.036919,-0.080760,-0.015557,0.017142,0.044878,0.109403

In [8]:
#Feature engineering

grid_data = grid_data.drop(['stab'], axis=1)

In [9]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
grid_data['stabf'] = le.fit_transform(grid_data['stabf'])

In [10]:
from sklearn.model_selection import train_test_split  

X = grid_data.drop(["stabf"], axis=1)
y = grid_data["stabf"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [11]:
from sklearn.preprocessing import StandardScaler

trans = StandardScaler()
X_train = trans.fit_transform(X_train)
X_test = trans.fit_transform(X_test)

In [12]:
def outcome(model, X_train, X_test, y_train, y_test): 
    model.fit(X_train, y_train)
    model_score = model.score(X_test, y_test)
    return model_score

In [13]:
#Question 14

RandomForestScore = outcome(model=RandomForestClassifier(random_state=42), X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
RandomForestScore

0.919

In [14]:
#Question 15
from xgboost import XGBClassifier
XGBOOSTScore = outcome(model=XGBClassifier(random_state=42), X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
XGBOOSTScore

0.919

In [15]:
#Question 16
import lightgbm as lgb
lgm = outcome(model=lgb.LGBMClassifier(random_state=42), X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
lgm

0.9355